apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: on-demand
    instanceTypes: ["t3.micro"]
    desiredCapacity: 2
    minSize: 1
    maxSize: 3